version: 2
mergeable:
  - when: pull_request.opened
name: "Greet a contributor"
validate: []
pass:
  - do: comment
payload:
  body: >
  'Testing welcome mssage - Thanks for creating a pull request! A maintainer will review your changes shortly. Please do not be discouraged if it takes a while'